apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app-namespace
  name: deploper
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"] 