apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-deploper
  namespace: app-namespace
subjects:
- kind: User
  name: developer
  apiGroup: ""
roleRef:
  kind: Role
  name: deploper
  apiGroup: ""